package main

import (
	"fmt"
	"os"
)

func GenExtra() {
	fileName := "extraType_gen.go"
	extraTypeGenFile, err := os.OpenFile(
		fileName,
		os.O_CREATE|os.O_WRONLY|os.O_TRUNC,
		0644,
	)
	if err != nil {
		log.Fatalw("failed to open file",
			"name", fileName,
			"error", err)
	}
	defer extraTypeGenFile.Close()
	extraTypeGenFile.Write(
		[]byte("// Code generated by \"lspgen\"; DO NOT EDIT\n"),
	)
	extraTypeGenFile.Write([]byte("package protocol\n"))

	for name, t := range TypesToGenerate {
		if t != nil {
			extraTypeGenFile.Write(
				[]byte(fmt.Sprintf("type %s any\n", name)),
			)
		}
	}
}
