package main

import (
	"fmt"
	"os"
	"sort"
)

func genExtra() {
	fileName := "extraType_gen.go"
	extraTypeGenFile, err := os.OpenFile(
		fileName,
		os.O_CREATE|os.O_WRONLY|os.O_TRUNC,
		0644,
	)
	if err != nil {
		log.Fatalw("failed to open file",
			"name", fileName,
			"error", err)
	}
	defer extraTypeGenFile.Close()
	extraTypeGenFile.Write(
		[]byte("// Code generated by \"lspgen\"; DO NOT EDIT\n"),
	)
	extraTypeGenFile.Write([]byte("package protocol\n"))

	tmp := []string{}

	for name := range TypesToGenerate {
		tmp = append(tmp, name)
	}

	sort.Strings(tmp)

	for _, name := range tmp {
		extraTypeGenFile.Write(
			[]byte(fmt.Sprintf("type %s struct{}\n", name)),
		)
	}
}
