name: Common check

on: [push]

jobs:
  build:
    name: Find trailing whitespace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: harupy/find-trailing-whitespace@master
